version: '3.1'
services:
  mysqldb:
    image: mysql
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
  mongodb:
    image: mongo
    container_name: 'mongodb'
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: unless-stopped
    logging:
      driver: "none"